# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f99fc785d5649af2ae0b7ab3c8c2cf22f34c954de241f76e1c9d3fb6054bc0084ed7cc687f409fa43bc1e735dba6a05c1651eda893bf992d2af68af5fe5abba

test:
  secret_key_base: 244f1a8dc49a0f49f73ca0db79adeb35043229e71c477b32da344fd883466670976a82c21d9a6a69995fc29bc66aaea90ccc2e1aaf00556304ef250a74644912

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
